apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app: example-service
spec:
  ports:
  - port: 8080
    nodePort:30001
  type: NodePort
  selector:
    app: example-pod
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: example-replica
  labels:
    app: example-replica
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example-pod
    spec:
      containers:
      - name: example-container
        image: nginx
        ports:
        - containerPort: 8080
